steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/devops-demo-repo/devops-demo:latest'
      - '.'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/devops-demo-repo/devops-demo:latest'
